import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {api} from './lib/api'; import './styles.css';

type User={id:string,name:string,email:string,role:'CLIENT'|'PROFESSIONAL',phone?:string};
type Pro={id:string,businessName:string,category:string,description?:string,user:{name:string},services:any[],availability:any[]};
function App(){const [user,setUser]=useState<User|null>(()=>JSON.parse(localStorage.getItem('user')||'null'));const [page,setPage]=useState('home');const [pros,setPros]=useState<Pro[]>([]);const [selected,setSelected]=useState<Pro|null>(null);const [msg,setMsg]=useState('');
useEffect(()=>{if(!user)api('/professionals').then(setPros).catch(()=>{});},[user]);
const logout=()=>{localStorage.clear();setUser(null);setPage('home')};
if(!user)return <><Header user={null} setPage={setPage}/>{page==='login'?<Login onLogin={setUser}/>:page==='register'?<Register onLogin={setUser}/>:<Home pros={pros} onSelect={p=>{setSelected(p);setPage('book')}} setPage={setPage}/>}</>;
return <><Header user={user} setPage={setPage} logout={logout}/>{msg&&<div className="toast">{msg}</div>}{user.role==='PROFESSIONAL'?<Professional page={page} setPage={setPage} setMsg={setMsg}/>:<Client page={page} setPage={setPage} selected={selected} setSelected={setSelected} setMsg={setMsg}/>}</>}
function Header({user,setPage,logout}:{user:User|null,setPage:any,logout?:any}){return <header><div className="brand" onClick={()=>setPage('home')}>Turnify</div><nav>{user?<><button onClick={()=>setPage('appointments')}>Mis turnos</button><button onClick={()=>setPage('profile')}>Perfil</button>{user.role==='PROFESSIONAL'&&<button onClick={()=>setPage('dashboard')}>Panel profesional</button>}<button className="outline" onClick={logout}>Salir</button></>:<><button onClick={()=>setPage('login')}>Ingresar</button><button onClick={()=>setPage('register')}>Crear cuenta</button></>}</nav></header>}
function Home({pros,onSelect,setPage}:{pros:Pro[],onSelect:(p:Pro)=>void,setPage:any}){return <main><section className="hero"><span className="pill">GESTIÓN DE TURNOS</span><h1>Reservá tu próximo turno de forma simple.</h1><p>Encontrá profesionales, elegí un servicio y reservá desde cualquier dispositivo.</p><button onClick={()=>setPage('register')}>Comenzar</button></section><h2>Profesionales disponibles</h2><div className="grid">{pros.map(p=><article className="card" key={p.id}><div className="avatar">{p.businessName[0]}</div><h3>{p.businessName}</h3><small>{p.category}</small><p>{p.description||'Servicios profesionales y turnos online.'}</p><button onClick={()=>onSelect(p)}>Ver servicios</button></article>)}</div></main>}
function Login({onLogin}:{onLogin:(u:User)=>void}){const [email,setEmail]=useState('cliente@turnify.local'),[password,setPassword]=useState('123456'),[error,setError]=useState('');async function go(e:any){e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));onLogin(d.user)}catch(e:any){setError(e.message)}}return <Auth title="Ingresar"><form onSubmit={go}>{error&&<p className="error">{error}</p>}<label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button>Ingresar</button></form></Auth>}
function Register({onLogin}:{onLogin:(u:User)=>void}){const [form,setForm]=useState({name:'',email:'',password:'',role:'CLIENT'});async function go(e:any){e.preventDefault();try{const d=await api('/auth/register',{method:'POST',body:JSON.stringify(form)});localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));onLogin(d.user)}catch(e:any){alert(e.message)}}return <Auth title="Crear cuenta"><form onSubmit={go}><label>Nombre<input required onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Contraseña<input required minLength={6} type="password" onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Tipo<select onChange={e=>setForm({...form,role:e.target.value})}><option value="CLIENT">Quiero reservar turnos</option><option value="PROFESSIONAL">Soy profesional</option></select></label><button>Crear cuenta</button></form></Auth>}
function Auth({title,children}:{title:string,children:any}){return <main className="auth"><div className="authbox"><h1>{title}</h1>{children}</div></main>}
function Client({page,setPage,selected,setSelected,setMsg}:{page:string,setPage:any,selected:Pro|null,setSelected:any,setMsg:any}){if(page==='profile')return <Profile/>;if(page==='book'&&selected)return <Booking p={selected} done={()=>{setMsg('Turno reservado correctamente');setPage('appointments')}}/>;if(page==='appointments')return <Appointments setMsg={setMsg}/>;return <main><section className="hero compact"><h1>Hola 👋</h1><p>Elegí un profesional para reservar tu turno.</p></section><Professionals onSelect={(p:any)=>{setSelected(p);setPage('book')}}/></main>}
function Professionals({onSelect}:{onSelect:any}){const [ps,setPs]=useState<Pro[]>([]);useEffect(()=>{api('/professionals').then(setPs)},[]);return <div className="grid">{ps.map(p=><article className="card" key={p.id}><div className="avatar">{p.businessName[0]}</div><h3>{p.businessName}</h3><small>{p.category}</small>{p.services.map(s=><div className="service" key={s.id}><b>{s.name}</b><span>${s.price}</span></div>)}<button onClick={()=>onSelect(p)}>Reservar</button></article>)}</div>}
function Booking({p,done}:{p:Pro,done:()=>void}){const [service,setService]=useState(p.services[0]?.id||''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[time,setTime]=useState('10:00'),[notes,setNotes]=useState(''),[reminder,setReminder]=useState('NONE');async function go(e:any){e.preventDefault();const s=p.services.find(x=>x.id===service);const end=new Date(`1970-01-01T${time}:00`);end.setMinutes(end.getMinutes()+s.duration);const endTime=end.toTimeString().slice(0,5);try{await api('/appointments',{method:'POST',body:JSON.stringify({professionalId:p.id,serviceId:service,date,startTime:time,endTime,notes,reminder})});done()}catch(err:any){alert(err.message)}}return <main className="auth"><div className="authbox wide"><h1>Reservar con {p.businessName}</h1><form onSubmit={go}><label>Servicio<select value={service} onChange={e=>setService(e.target.value)}>{p.services.map(s=><option key={s.id} value={s.id}>{s.name} · ${s.price}</option>)}</select></label><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Hora<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><label>Aclaraciones<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="¿Hay algo que el profesional deba saber?"/></label><label>Recordatorio<select value={reminder} onChange={e=>setReminder(e.target.value)}><option value="NONE">Sin recordatorio</option><option value="EMAIL">Email</option><option value="WHATSAPP">WhatsApp</option><option value="BOTH">Email + WhatsApp</option></select></label><button>Confirmar turno</button></form></div></main>}
function Appointments({setMsg}:{setMsg:any}){const [a,setA]=useState<any[]>([]);const load=()=>api('/appointments').then(setA);useEffect(load,[]);async function cancel(id:string){await api('/appointments/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:'CANCELLED'})});setMsg('Turno cancelado');load()}return <main><h1>Mis turnos</h1><div className="list">{a.map(x=><article className="appointment" key={x.id}><div><b>{x.service.name}</b><p>{new Date(x.date).toLocaleDateString('es-AR')} · {x.startTime}</p><small>Profesional: {x.professional.user.name}</small>{x.notes&&<p>📝 {x.notes}</p>}</div><span className={'status '+x.status.toLowerCase()}>{x.status}</span>{x.status!=='CANCELLED'&&<button className="danger" onClick={()=>cancel(x.id)}>Cancelar</button>}</article>)}</div></main>}
function Profile(){const [u,setU]=useState<any>(null);const [name,setName]=useState(''),[phone,setPhone]=useState('');useEffect(()=>{api('/profile').then(d=>{setU(d);setName(d.name);setPhone(d.phone||'')})},[]);if(!u)return <main>Cargando...</main>;return <main className="auth"><div className="authbox"><h1>Mi perfil</h1><form onSubmit={async e=>{e.preventDefault();await api('/profile',{method:'PUT',body:JSON.stringify({name,phone})});alert('Perfil actualizado')}}><label>Nombre<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Teléfono<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Email<input disabled value={u.email}/></label><button>Guardar cambios</button></form></div></main>}
function Professional({page,setPage,setMsg}:{page:string,setPage:any,setMsg:any}){if(page==='profile')return <Profile/>;if(page==='appointments'||page==='dashboard')return <ProDashboard setMsg={setMsg}/>;if(page==='services')return <Services/>;return <ProDashboard setMsg={setMsg}/>}
function ProDashboard({setMsg}:{setMsg:any}){const [a,setA]=useState<any[]>([]);const load=()=>api('/appointments').then(setA);useEffect(load,[]);async function status(id:string,status:string){await api('/appointments/'+id+'/status',{method:'PATCH',body:JSON.stringify({status})});setMsg('Turno actualizado');load()}return <main><section className="hero compact"><span className="pill">PANEL PROFESIONAL</span><h1>Gestioná tus turnos.</h1><p>Visualizá solicitudes, confirmá y cancelá turnos.</p></section><h2>Próximos turnos</h2><div className="list">{a.map(x=><article className="appointment" key={x.id}><div><b>{x.client.name}</b><p>{x.service.name} · {new Date(x.date).toLocaleDateString('es-AR')} · {x.startTime}</p><small>{x.client.email} {x.client.phone&&'· '+x.client.phone}</small>{x.notes&&<p>📝 {x.notes}</p>}</div><span className={'status '+x.status.toLowerCase()}>{x.status}</span><div><button onClick={()=>status(x.id,'CONFIRMED')}>Confirmar</button> <button className="danger" onClick={()=>status(x.id,'CANCELLED')}>Cancelar</button></div></article>)}</div></main>}
function Services(){return <main><h1>Servicios</h1><p>La gestión de servicios está disponible desde la API del MVP y será incorporada al panel visual en la siguiente iteración.</p></main>}
createRoot(document.getElementById('root')!).render(<App/>);
